# Generated by Django 3.2 on 2023-09-24 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20230922_1025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todomodel',
            old_name='duedte',
            new_name='duedate',
        ),
    ]
